[package]
name = "bevy_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
rand = "0.8.5"
bevy_screen_diags = "0.6.0"

[profile.dev.package."*"]
opt-level = 3